//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAIHOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAIHOC()
        {
            this.KHOAHOCs = new HashSet<KHOAHOC>();
        }
    
        public int MABAIHOC { get; set; }
        public Nullable<int> MAKHOAHOC { get; set; }
        public string TENBAIHOC { get; set; }
        public string ANHBAIHOC { get; set; }
        public string NOIDUNG { get; set; }
        public string NOIDUNG1 { get; set; }
        public string NOIDUNG2 { get; set; }
    
        public virtual KHOAHOC KHOAHOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHOAHOC> KHOAHOCs { get; set; }
    }
}
