//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOAHOC_BAIHOC
    {
        public int MAKH_BH { get; set; }
        public Nullable<int> MaKhoaHoc { get; set; }
        public Nullable<int> MaBaiHoc { get; set; }
    
        public virtual BAIHOC BAIHOC { get; set; }
        public virtual KHOAHOC KHOAHOC { get; set; }
    }
}
