//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOAHOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHOAHOC()
        {
            this.KHOAHOC_BAIHOC = new HashSet<KHOAHOC_BAIHOC>();
        }
    
        public int MaKhoaHoc { get; set; }
        public string TenKhoaHoc { get; set; }
        public string TacGia { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<decimal> GiaKhoaHoc { get; set; }
        public Nullable<decimal> GiaKhuyenMai { get; set; }
        public string DoiTuong { get; set; }
        public string Anh { get; set; }
        public string Linkvideo { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHOAHOC_BAIHOC> KHOAHOC_BAIHOC { get; set; }
    }
}
