//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUOIDUNG()
        {
            this.BINHLUANs = new HashSet<BINHLUAN>();
            this.BINHLUANBLOGs = new HashSet<BINHLUANBLOG>();
            this.BLOGs = new HashSet<BLOG>();
            this.BLOGs1 = new HashSet<BLOG>();
            this.TRALOIs = new HashSet<TRALOI>();
        }
    
        public int MANGUOIDUNG { get; set; }
        public string TAIKHOAN { get; set; }
        public string MATKHAU { get; set; }
        public string TENDANGNHAP { get; set; }
        public string EMAIL { get; set; }
        public string DIACHI { get; set; }
        public string SOCMND { get; set; }
        public string SODIENTHOAI { get; set; }
        public string AnhNguoiDung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BINHLUAN> BINHLUANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BINHLUANBLOG> BINHLUANBLOGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BLOG> BLOGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BLOG> BLOGs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRALOI> TRALOIs { get; set; }
    }
}
