//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBAIHOC
    {
        public int MaBaiHoc { get; set; }
        public string TenBaiHoc { get; set; }
        public string Anh { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> MaKhoahoc { get; set; }
    
        public virtual tbKHOAHOC tbKHOAHOC { get; set; }
    }
}
